CREATE TABLE APP_USERS (
    USERNAME VARCHAR2(50) PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL
);

INSERT INTO APP_USERS VALUES ('admin', '1234');

COMMIT;

CREATE TABLE FORM_DATA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EDAD NUMBER,
    CORREO VARCHAR2(100),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

COMMIT;